# Generated by Django 3.0.2 on 2020-02-01 05:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('street_biter_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='street_biter',
            name='details',
            field=models.CharField(default='add details', max_length=900),
        ),
        migrations.AddField(
            model_name='street_biter',
            name='latitude',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='street_biter',
            name='longitude',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='street_biter',
            name='species',
            field=models.CharField(default='add details', max_length=20),
        ),
        migrations.AddField(
            model_name='street_biter',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
