# Generated by Django 3.0.2 on 2020-02-06 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('street_biter_app', '0002_auto_20200201_0508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='street_biter',
            name='latitude',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='street_biter',
            name='longitude',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=10),
        ),
    ]
