# Generated by Django 3.0.2 on 2020-02-06 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('street_biter_app', '0004_auto_20200206_0353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='street_biter',
            name='latitude',
            field=models.DecimalField(decimal_places=16, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='street_biter',
            name='longitude',
            field=models.DecimalField(decimal_places=16, default=0, max_digits=16),
        ),
    ]
